version: '2'
services:
  db:
    container_name: dbodoo
    image: postgres:14
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=devx340Test@    
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data
  odoo:
    image: odoo:15
    user: root
    container_name: odoo15
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=devx340Test@
    volumes:
      - ./odoo_addons:/mnt/extra-addons
    restart: always
    build: .